version: '3.8'

services:
  interface_openai:
    build:
      context: .
      dockerfile: Dockerfile
    image: interface_openia:1.0
    volumes:
      - db_volume:/workplace/app/data
    command: sh -c "python3 run.py & tail -f /dev/null"



volumes:
  db_volume:
